spring:
  datasource:
    url: jdbc:mysql://115.190.11.188:3306/yishao?useSSL=false&serverTimezone=UTC
    username: yishao
    password: alexyavin666
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      uri: mongodb://root:alexyavin666@115.190.11.188:27017/admin